-- 1. Установите arend, следуя инструкциям на странице https://arend-lang.github.io/documentation/getting-started/download
--    В IDEA можно просто импортировать данный проект

-- 2. Определите аналоги следующих функций на языке Haskell
{- Haskell:
   second :: Nat -> Nat -> Nat -> Nat
   second _ y _ = y

   apply :: (Nat -> Nat) -> Nat -> Nat
   apply f x = f x

   compose :: (Nat -> Nat) -> (Nat -> Nat) -> Nat -> Nat
   compose f g x = f (g x)

   flip :: (Nat -> Nat -> Nat) -> Nat -> Nat -> Nat
   flip f x y = f y x

   second' = flip (second 0)
-}
\func second (_ y _ : Nat) => y
\func apply (f : Nat -> Nat) (x : Nat) => f x
\func compose (f : Nat -> Nat) (g : Nat -> Nat) (x : Nat) => f (g x)
\func flip (f : Nat -> Nat -> Nat) (x y : Nat) => f y x
\func second' => flip (second 0)

-- 3. Расставьте приоритеты функций f1, f2, f3, f4, f5 и f6 так, чтобы функция test проходила тайпчекинг

\import lect01 \hiding (+, *)

\func f1 (x y : Nat) => x
\func f2 : Nat => 0
\func \infix 1 f3 (f : Nat -> Nat) (z : Nat) : Int => 0
\func f4 : Nat => 0
\func \infixl 2 f5 => f1
\func f6 => f4

\func test => f1 f2 f3 f4 f5 f6

-- 4. Определите функцию if, аналогичную следующей функции:
{- Haskell:
   if :: Bool -> Bool -> Bool -> Bool
   if True t _ = t
   if False _ e = e
-}
\func if (cond x y : Bool) : Bool \elim cond
  | true => x
  | false => y

-- 5. Определите || через if

\func \infixr 2 || (x y : Bool) : Bool => if x true y

-- 6. Определите возведение в степень и факториал для натуральных чисел

\open Nat \hiding (-, div) -- Здесь лежат + и *

\func \infixr 8 ^ (x y : Nat) : Nat \elim y
  | 0 => 1
  | suc y => x ^ y

\func fac (x : Nat) : Nat \elim x
  | 0 => 1
  | suc x1 => suc x1 * fac x1

-- 7. Определите mod и gcd

\func mod (x y : Nat) => x - y * div x y  -- x, если y=0
-- \func mod-x0 (x : Nat) : mod x 0 = x \elim x
--   | 0 => mod 0 0 = 0
--   | suc x =>

\func gcd (x y : Nat) : Nat => aux (suc x) x y
    \where {
      \func aux (fuel x y : Nat) : Nat \elim fuel
        | 0 => 0  -- never
        | suc fuel => \case x, y \with {
          | x, 0 => x
          | 0, y => y
          | x, y => aux fuel (mod x y) (mod y x)
        }
    }

\func test-gcd-5-2-1 : gcd 5 2 = 1 => idp
\func test-gcd-5-6-5 : gcd 5 6 = 1 => idp
\func test-gcd-2-0-2 : gcd 2 0 = 2 => idp
\func test-gcd-12-18-6 : gcd 12 18 = 6 => idp
\func test-gcd-18-12-6 : gcd 18 12 = 6 => idp
\func test-gcd-0-0-0 : gcd 0 0 = 0 => idp
