\import Data.Bool
\import Data.Maybe
\import Function (o)
\import Logic
\import hw01 (gcd)
\import lect06

-- 1. Определите функцию swap несколькими способами

-- При помощи \cowith и доступа к полям
\func swap {A B : \Type} (p : Pair A B) : Pair B A \cowith
  | fst_ => p.snd_
  | snd_ => p.fst_

-- При помощи \new и паттерн матчинга
\func swap' {A B : \Type} (_ : Pair A B) : Pair B A \elim
  | (a,b) => \new Pair { | fst_ => b | snd_ => a }

-- При помощи \new и доступа к полям
\func swap'' {A B : \Type} (p : Pair A B) : Pair B A => \new Pair { | fst_ => p.snd_ | snd_ => p.fst_ }

-- 2. Докажите, что swap (swap p) = p

\func swap-involutive {A B : \Type} (p : Pair A B) : swap (swap p) = p => idp

-- 3. Докажите, что тип PosNat 0 пустой, а тип PosNat 1 нет

\func zero-isNotPos (p : PosNat 0) : Empty => \case p.p \with {}

\func isPos1 : isPos 1 = true => idp
\func one-isPos : PosNat 1 => \new PosNat 1 (So.toSo idp)

-- 4. Определите \record, состоящий из пар взаимно простых натуральных чисел
--    Определите тип, состоящий из натуральных чисел, взаимно простых с 60

\record CoprimePair (a b : Nat) (p : gcd a b = 1)
\record Coprime60 (a : Nat) (p : gcd a 60 = 1)

-- 5. Закончите определение класса монад
--    Этот класс должен содержать все монадные законы и реализовывать все поля из класса функторов

\class Monad \extends Functor {
  | return {A : \Type} : A -> F A
  | \infixl 2 >>= {A B : \Type} : F A -> (A -> F B) -> F B
  | left-identity {A B : \Type} (a : A) (h : A -> F B) : return a >>= h = h a
  | right-identity {A : \Type} (m : F A) : m >>= return = m
  | >>=assoc {A B C : \Type} (m : F A) (g : A -> F B) (h : B -> F C) : (m >>= g) >>= h = m >>= (\lam x => g x >>= h)
  \default fmap {A B : \Type} (f : A -> B) (m : F A) : F B => m >>= (return o f)
  \default fmap-id {A : \Type} (x : F A) : fmap (\lam a => a) x = x => {?}
  \default fmap-comp {A B C : \Type} (f : B -> C) (g : A -> B) (x : F A) : fmap (\lam a => f (g a)) x = fmap f (fmap g x) => {?}
}

-- 6. Определите \instance Monad для Maybe

\instance MonadMaybe : Monad Maybe
  | return => Maybe.just
  | >>= {A B : \Type} (m : Maybe A) (h : A -> Maybe B) : Maybe B \elim m {
    | nothing => nothing
    | just a => h a
  }
  | left-identity {A B : \Type} (a : A) (h : A -> Maybe B) : Maybe.just a >>= h = h a => idp
  | right-identity {A : \Type} (m : Maybe A) : m >>= Maybe.just = m \elim {
    | nothing => idp
    | just a => idp
  }
  | >>=assoc {A B C : \Type} (m : Maybe A) (g : A -> Maybe B) (h : B -> Maybe C) : (m >>= g) >>= h = m >>= (\lam x => g x >>= h) \elim m {
    | nothing => idp
    | just a => idp
  }


-- 7. Определите \instance Monad для State и State'

\record State (S A : \Type)
  | state : S -> \Sigma S A

\data State' (S A : \Type)
  | state' (S -> \Sigma S A)
