\import Data.Bool
\import Data.List (++, List, contains, length, ::)
\import Function.Meta
\import Logic
\import Meta
\import Paths
\import Paths.Meta
\import lect07
\open Nat(+,*)


-- 1. Определите предикат принадлежности элемента списку

\data In {A : \Type} (a : A) (xs : List A)
  | in (pref suf : List A) (pref ++ a :: suf = xs)

\func example : In 2 (1 :: 2 :: 3 :: 4 :: List.nil) => In.in (1 :: List.nil) (3 :: 4 :: List.nil) idp

-- Optional:
-- 2. Докажите эквивалентность четырех различных определений LessOrEq: lessOrEq, lessOrEq', LessOrEq и LessOrEq'


-- 3. Определите рефлексивное транзитивное замыкание отношения
--    То есть ReflTransClosure R -- это минимальное рефлексивное и транзитивное отношение, содержащее R

\data ReflTransClosure {A : \Type} (R : A -> A -> \Type) (x y : A)


-- 4. Докажите, что если R уже рефлексивно и транзитивно, то ReflTransClosure R эквивалентно R

\func \infix 4 <-> (A B : \Type) => \Sigma (A -> B) (B -> A)

\func ReflTransClosure-lem {A : \Type} (R : A -> A -> \Type)
                           (refl : \Pi (x : A) -> R x x)
                           (trans : \Pi (x y z : A) -> R x y -> R y z -> R x z)
  : \Pi (x y : A) -> R x y <-> ReflTransClosure R x y
  => {?}


-- 5. Определите предикат Sublist xs ys на списках, означающий "список xs является подсписком ys"

\data Sublist {A : \Type} (xs ys : List A)
--   | sublist (p : A -> Bool) (filter p ys = xs)
  | sublist (a : A) (In a xs -> In a ys)

-- 6. Докажите, что Sublist (filter p xs) xs для любых p и xs

\func helper {A : \Type} (a : A) (xs : List A) (i : In a xs) (p : A -> Bool) (q : So (p a)) : In a (filter p xs) => {?}

-- 7. Определите filter через if, а не через \case
--    Докажите для этой версии filter лемму filter-lem

\func filter' {A : \Type} (p : A -> Bool) (xs : List A) : List A => {?}

\func filter-lem {A : \Type} (p : A -> Bool) (xs : List A) : LessOrEq (length (filter' p xs)) (length xs) => {?}


-- 8. Закончите определение функции \func BoolFuncLem (f : Bool -> Bool) (x : Bool) : f (f (f x)) = f x из лекции

\func BoolFuncLem (f : Bool -> Bool) (x : Bool) : f (f (f x)) = f x
  => cases (f x arg addPath, f true arg addPath, f false arg addPath) \with {
    | false, p, false, p1, false, p2 => rewrite (p2, p2) idp
    | false, p, false, p1, true, p2 => rewrite (p2, p1) idp
    | false, p, true, p1, false, p2 => rewrite (p2, p2) idp
    | false, p, true, p1, true, p2 => \case x \as y, p : f y = false \return f (f false) = false \with {
      | false, p3 => \case inv p3 *> p2
      | true, p3 => \case inv p3 *> p1
    }
    | true, p, false, p1, false, p2 => {?}
    | true, p, false, p1, true, p2 => {?}
    | true, p, true, p1, false, p2 => {?}
    | true, p, true, p1, true, p2 => {?}
  }

-- 9. Докажите, что предикат isEven разрешим

\func isEven (n : Nat) => \Sigma (k : Nat) (n = 2 * k)

\func isEven-dec : DecPred isEven => \lam a => {?}


-- 10. Докажите, что если равенство элементов A разрешимо, то и равенство элементов List A тоже разрешимо

\instance ListEq {A : \Type} (dec : Eq A) : Eq (List A)
  | decideEq => {?}


-- 11. Докажите, что функции FromBoolToDec и FromDecToBool взаимно обратны

\func bdb {A : \Type} (p : A -> Bool) : FromDecToBool (FromBoolToDec p) = p => {?}

-- Мы не можем доказать, что FromBoolToDec (FromDecToBool P) = P,
-- но мы можем доказать более слабое утверждение: эти предикаты логически эквивалентны
-- Для этого введем эквивалентность предикатов

\func dbd {A : \Type} (P : \Sigma (P : A -> \Type) (DecPred P))
  : \Pi (x : A) -> (FromBoolToDec (FromDecToBool P)).1 x <-> P.1 x
  => {?}


-- Optional:
-- 12. Парадокс Рассела показывает, что не существует множества всех множеств
--     Если такое множество существует, то мы можем определить множество B, состоящее из множеств, не содержащих себя
--     Тогда B принадлежит себе тогда и только тогда, когда оно себе не принадлежит
--     Отсюда следует противоречие
--
--     Теорема Кантора утверждает, что не существует множества X с сюръекцией из X в множество подмножеств X
--     Её доказательство также конструирует утверждение, которое верно тогда и только тогда, когда оно ложно
--     Верно, что в общем случае существование такого утверждения влечет противоречие
--     Это легко доказать при помощи исключенного третьего, но утверждение верно и без него
--     Докажите этот факт
\func contrProp {A : \Type} (p : A -> Not A) (q : Not A -> A) : Empty => p1 $ q p1
    \where {
      \func p1 : Not A => \lam a => p a a
    }
