\import Data.Array
\import Data.Or
\import Function (o)
\import Function.Meta
\import Logic
\import Logic.Meta
\import Order.LinearOrder
\import hw07 (contrProp)
\import lect01 (-)
\import lect05 (unext)
\import lect11 (equality=>equivalence)
\import lect12 \hiding (Int', pos, neg)
\import Arith.Nat (NatSemiring)
\import Equiv
\import Function.Meta
\import Logic
\import Order.LinearOrder
\import Paths
\import lect13 (EqArray, In)

-- 1. Определите функцию negPred : Int -> Int такую, что negPred x = x, если x > 0, и negPred x = x - 1, если x <= 0

\func negPred (x : Int) : Int \elim x
  | pos (suc n) => suc n
  | pos 0 => neg 1
  | neg n => neg (suc n)

-- 2. Определите функции сложения и умножения для Int

\func \infixl 6 + (x y : Int) : Int \with
  | pos n, pos n1 => pos (n Nat.+ n1)
  | pos n, neg (suc n1) => \case LinearOrder.trichotomy n (suc n1) \with {
    | less _ => neg $ (suc n1) - n
    | equals _ => pos 0
    | greater _ => pos $ n - (suc n1)
  }
  | neg (suc n), pos n1 => \case LinearOrder.trichotomy (suc n) n1 \with {
    | less _ => pos $ n1 - (suc n)
    | equals _ => pos 0
    | greater _ => neg $ (suc n) - n1
  }
  | neg (suc n), neg (suc n1) => neg ((suc n) Nat.+ (suc n1))

\func test+1 : 0 + neg 1 = neg 1 => idp
\func test+3 : 1 + neg 1 = 0 => idp
\func test+4 : 1 + pos 0 = 1 => idp
\func test+5 : neg 1 + neg 1 = neg 2 => idp
\func test+6 : neg 1 + pos 0 = neg 1 => idp
\func test+7 : neg 1 + 1 = 0 => idp

\func \infixl 7 * (x y : Int) : Int \with
  | pos n, pos n1 => pos (n Nat.* n1)
  | pos n, neg (suc n1) => neg (n Nat.* (suc n1))
  | neg (suc n), pos n1 => neg ((suc n) Nat.* n1)
  | neg (suc n), neg (suc n1) => pos ((suc n) Nat.* (suc n1))

\func test*1 : 0 * neg 1 = 0 => idp
\func test*3 : 1 * neg 1 = neg 1 => idp
\func test*4 : 1 * pos 0 = 0 => idp
\func test*5 : neg 1 * neg 1 = pos 1 => idp
\func test*6 : neg 1 * pos 0 = 0 => idp
\func test*7 : neg 1 * 1 = neg 1 => idp
\func test*8 : neg 2 * neg 2 = pos 4 => idp
\func test*9 : neg 2 * pos 0 = 0 => idp
\func test*1- : neg 2 * 2 = neg 4 => idp

-- 3. Определите тип данных BinNat для бинарных натуральных чисел
--    У него должно быть три конструктора: для 0, для чисел вида 2*n и чисел вида 2*n+1
--    Такой тип данных содержит несколько различных представлений для нуля
--    Используйте типы данных с условиями, чтобы вычислительно отождествить различные нули

\data BinNat
  | zero
  | x2 BinNat \with { zero => zero }
  | x2+1 BinNat

-- 4. Докажите, что функция pred сюръективна

\func pred (n : Nat) : Nat
  | 0 => 0
  | suc n => n

\func pred-is-sur : isSurj pred => \lam b => inP (suc b, idp)

-- 5. Докажите, что функция suc не сюръективна

-- TruncP.remove' is \lemma
\func not-truncPEmpty : Not (TruncP Empty) => \lam (inP a) => a

\func suc-is-not-sur (p : isSurj suc) : Empty => not-truncPEmpty $ TruncP.map (p 0) (\lam (a, q) => \case q \with {})

-- 6. Пусть f : A -> B и g : B -> C ─ некоторые функции
--    Докажите, что если f и g сюръективны, то g o f также сюръективна
--    Докажите, что если g o f сюръективна, то g также сюръективна

\func TruncP-flatMap {A B : \Type} (t : TruncP A) (f : A -> TruncP B) : TruncP B \elim t
  | inP a => f a

\func o-sur {A B C : \Type} (f : A -> B) (g : B -> C) (p : isSurj f) (q : isSurj g) : isSurj (g o f) =>
  \lam c => TruncP-flatMap (q c) $ \lam (b, r) => TruncP.map (p b) (\lam (a, s) => (a, pmap g s *> r))

\func o-sur' {A B C : \Type} (f : A -> B) (g : B -> C) (p : isSurj (g o f)) : isSurj g =>
  \lam b => TruncP.map (p b) $ \lam (a, q) => (f a, q)

-- 7. Определите множество конечных подмножеств множества A,
--    то есть списков элементов A с точностью до перестановок и повторений элементов

\truncated \data Set (A : \Set) : \Set
  | set (Array A)
  | ~equiv {a b : Array A} (EqArray a b) : set a = set b

\func a : Array Nat => \new DArray {
  | len => 1
  | at => \lam 0 => 1
}

\func b : Array Nat => \new DArray {
  | len => 1
  | at => \lam 0 => 0
}

\func c : Array Nat => \new DArray {
  | len => 2
  | at => \case __ \with {
    | 0 => 1
    | 1 => 1
  }
}

\func a=a : (set a) = (set a) => idp
\func a=a' : (set a) = (set a) => Set.~equiv {Nat} {a} {a} (\lam _ => (\lam b => b, \lam b => b))
-- \func a/=b : (set a) /= (set b) => \lam p => unext p {?}

\func in-a {n : Nat} (p : In n a) : n = 1 \elim p
  | inP (0, q) => inv q

\func in-c {n : Nat} (p : In n c) : n = 1 \elim p
  | inP (0, q) => inv q
  | inP (1, q) => inv q

\func a=c : (set a) = (set c) => Set.~equiv {Nat} {a} {c} (\lam d => (
  \lam q => inP (0, \have p' : d = 1 => in-a q \in inv p'),
  \lam q => inP (0, \have p' : d = 1 => in-c q \in inv p')
                                                                     ))

-- 8. Докажите теорему Кантора

-- Теорема Кантора говорит, что для любого множества A мощность множества его подмножеств строго больше, чем мощность A

-- Множество подмножеств можно определить следующим образом:

\func Subs (A : \Set) => A -> \Prop

-- Формально утверждение теоремы Кантора состоит из двух частей:
-- "существует инъекция из A в Subs A" и "не существует сюръекции из A в Subs A"
-- Здесь поможет contrProp из hw07

\func cantor1 (A : \Set) : \Sigma (f : A -> Subs A) (isInj f) => (=, =-isInj)

\func cantor2 (A : \Set) (f : A -> Subs A) (p : isSurj f) : Empty =>
  not-truncPEmpty $ TruncP.map (p contradict) \lam (a, q) =>
      \have | equivv : Equiv => equality=>equivalence (unext q a)
      \in contrProp {(f a) a} (\lam faa => \lam _ => equivv faa faa)
          (\lam t => equivv.sec t)
  \where {
    \func contradict (a : A) => Not ((f a) a)

    --     \func setSingleton (a a' : A): \Prop => a = a'
    --     \func emptySet (a : A) : \Prop => a = a
    --

    --     \func equivv (a : A) (q : f a = contradict) : Equiv {f a a} {contradict a} => equality=>equivalence {f a a} {contradict a} (unext q a)
    --
--     -- f(A) = setSignleton ?
    --
--     \func finv (a : A) : TruncP (\Sigma (a1 : A) (f a1 = setSingleton a)) => p (setSingleton a)
    --
--     \func finv' (a : A) : TruncP A => TruncP.map (finv a) \lam b => b.1
    --
--     --     \func obvious : isInj finv => {?}
    --
--     --     \func absurd (q : isSurj finv') : Empty => TruncP.map emptySetInv (\lam (a, r) => q (inP a))
    --
--     \func emptySetInv : TruncP (\Sigma (a1 : A) (f a1 = emptySet)) => p emptySet
    --
--     -- exists A -> B surj, exists B -> A inj => exists A <-> B bijection?
  }

-- Optional
-- 9. Постройте функции Nat -> BinNat и BinNat -> Nat и докажите, что они взаимно обратны

\func odd-or-even (n : Nat) : Or (\Sigma (x : Nat) (n = x Nat.* 2 Nat.+ 1)) (\Sigma (x : Nat) (n = x Nat.* 2)) \with
  | 0 => inr (0, idp)
  | suc 0 => inl (0, idp)
  | suc (suc x) => \case odd-or-even x \with {
    | inl (n, p) => inl (suc n, pmap (suc $ suc __) p)
    | inr (n, p) => inr (suc n, pmap (suc $ suc __) p)
  }

-- \func NatToBinNat (n : Nat) : BinNat \elim n
--   | 0 => zero
--   | suc n => \case odd-or-even n \with {
--     | inl (n1, _) => x2 (NatToBinNat n)
--     | inr (n1, _) => x2 (NatToBinNat n)
--   }

\func helper (n : Nat) (fuel : Nat) : BinNat \with
  | _, 0 => zero
  | 0, _ => zero
  | suc n, suc fuel => \case odd-or-even (suc n) \with {
    | inl (n, p) => x2+1 (helper n fuel)
    | inr (n, p) => x2 (helper n fuel)
  }

\func NatToBinNat (n : Nat) : BinNat => helper n (suc n)

\func BinNatToNat (b : BinNat) : Nat \elim b
  | zero => 0
  | x2 b => 2 Nat.* BinNatToNat b
  | x2+1 b => 2 Nat.* BinNatToNat b Nat.+ 1

\func nbn (n : Nat) : BinNatToNat (NatToBinNat n) = n => {?}

\func bnb (b : BinNat) : NatToBinNat (BinNatToNat b) = b => {?}
