\import Data.Bool
\import Function
\import Logic
\import Paths
\import Relation.Equivalence
\import Set
\import lect13


-- 1. Докажите, что add x (add x s) = add x s и add x (add y s) = add y (add x s)

\func add-idemp {S : SetSpec} (x : S.A) (s : S) : add x (add x s) = add x s =>
  S.set-ext (\lam _ => (
    \lam i => \case S.add-prop i \with {
      | byLeft x=a => transport (S.isElem __ (add x s)) x=a S.add-head
      | byRight b => b
    },
    \lam i => S.add-tail i
  ))

\func add-swap {S : SetSpec} (x y : S.A) (s : S) : add x (add y s) = add y (add x s) =>
  S.set-ext (\lam a => (uni-swap x y a, uni-swap y x a))
  \where {
    \func uni-swap (x1 y1 : S.A) (a : S.A) : a S.`isElem` add x1 (add y1 s) -> a S.`isElem` add y1 (add x1 s) =>
      \lam i => \case S.add-prop i \with {
        | byLeft x1=a => transport (S.isElem __ (add y1 (add x1 s))) x1=a (S.add-tail S.add-head)
        | byRight a_in_y1+s => \case S.add-prop a_in_y1+s \with {
          | byLeft y1=a => transport (S.isElem __ (add y1 (add x1 s))) y1=a S.add-head
          | byRight a_in_s => S.add-tail (S.add-tail a_in_s)
        }
      }
  }


-- 2. Докажите, что множество подмножеств является инстансом SetSpec

\instance subsets {A : \Set} : SetSpec {A} (A -> \Prop)
  | isElem => {?}
  | set-ext => {?}
  | empty => {?}
  | empty-prop => {?}
  | add => {?}
  | add-head => {?}
  | add-tail => {?}
  | add-prop => {?}

-- 3. Докажите, что множество подмножеств является наибольшим инстансом, то есть любой другой вкладывается в него

\func subsets-largest (S : SetSpec) : \Sigma (f : S -> S.A -> \Prop) (isInj f) => {?}


-- 4. Определите функцию isEmpty для ArraySet и для произвольного конечного множества

\func isEmptyArraySet {A : \Set} (xs : ArraySet A) : Bool \elim xs
  | in~ a => {?}
  | ~-equiv x y r i => {?}

\func isEmptySet {S : FinSetSpec} (s : S) : Bool => {?}


-- 5. Определите функцию union {A : \Set} : S -> S -> S для ArraySet и для произвольного S (удовлетворяющего FinSetSpec)


-- 6. Определите функцию intersection {A : DecSet} : S -> S -> S для ArraySet и для произвольного S (удовлетворяющего FinSetSpec)


-- 7. Мы не можем определить функцию size в общем случае, но мы можем определить предикат S -> Nat -> \Prop,
--    соответствующий \lam xs n => size xs <= n
--    a) Определите описанный предикат
--    b) Определите функцию size из лекции
--    c) Докажите, что size-le эквивалентно определению через size, если A -- разрешимо и S -- конечно

\func size-le {S : SetSpec} (s : S) (n : Nat) : \Prop => {?}

\func size {A : DecSet} {S : FinSetSpec {A}} (s : S) : Nat => {?}


-- Optional
-- 8. Определите предикат isFin : \Type -> \Prop так,
--    чтобы множество \Sigma (P : A -> \Prop) (isFin (\Sigma (a : A) (P a))) удовлетворяло FinSetSpec
--    Определите этот инстанс


-- Optional
-- 9. Определите NubArraySet (ArraySet без повторений) и инстанс FinSetSpec для него
