\import Arith.Nat
\import Data.Array (++, Index, filter, find, index-dec, keep, nub, nub-isInj, nub-isSurj, nub-preimage, nub_id)
\import Data.Bool
\import Data.Or
\import Equiv
\import Equiv.Univalence
\import Function
\import Function.Meta
\import HLevel
\import Logic
\import Logic.Meta
\import Meta
\import Order.PartialOrder
\import Paths
\import Paths.Meta
\import Relation.Equivalence
\import Set
\import Set.Fin
\import hw12 (TruncP-flatMap, not-truncPEmpty)
\import lect05 (unext)
\import lect11 (equality=>equivalence)
\import lect13


-- 1. Докажите, что add x (add x s) = add x s и add x (add y s) = add y (add x s)

\func add-idemp {S : SetSpec} (x : S.A) (s : S) : add x (add x s) = add x s =>
  S.set-ext (\lam _ => (
    \lam i => \case S.add-prop i \with {
      | byLeft x=a => transport (S.isElem __ (add x s)) x=a S.add-head
      | byRight b => b
    },
    \lam i => S.add-tail i
  ))

\func add-swap {S : SetSpec} (x y : S.A) (s : S) : add x (add y s) = add y (add x s) =>
  S.set-ext (\lam a => (uni-swap x y a, uni-swap y x a))
  \where {
    \func uni-swap (x1 y1 : S.A) (a : S.A) : a S.`isElem` add x1 (add y1 s) -> a S.`isElem` add y1 (add x1 s) =>
      \lam i => \case S.add-prop i \with {
        | byLeft x1=a => transport (S.isElem __ (add y1 (add x1 s))) x1=a (S.add-tail S.add-head)
        | byRight a_in_y1+s => \case S.add-prop a_in_y1+s \with {
          | byLeft y1=a => transport (S.isElem __ (add y1 (add x1 s))) y1=a S.add-head
          | byRight a_in_s => S.add-tail (S.add-tail a_in_s)
        }
      }
  }


-- 2. Докажите, что множество подмножеств является инстансом SetSpec

\instance subsets {A : \Set} : SetSpec {A} (A -> \Prop)
  | isElem (a : A) (s : A -> \Prop) : \Prop => s a
  | set-ext {xs ys : A -> \Prop} (p : \Pi (a : A) -> xs a <-> ys a) : xs = ys =>
  \have
    q (a : A) : xs a = ys a => <->_=.1 (p a)
  \in ext q
  | empty : A -> \Prop => \lam a => Empty
  | empty-prop {a : A} : Not (empty a) => \lam e => e
  | add (a : A) (s : A -> \Prop) : A -> \Prop => \lam a1 => (a = a1) || s a1
  | add-head {x : A} {xs : A -> \Prop} : (add x xs) x => byLeft idp
  | add-tail {x y : A} {xs : A -> \Prop} (p : xs x) : (add y xs) x => byRight p
  | add-prop {x y : A} {xs : A -> \Prop} (p : (add x xs) y) : (x = y) || xs y => p

-- 3. Докажите, что множество подмножеств является наибольшим инстансом, то есть любой другой вкладывается в него

\func subsets-largest (S : SetSpec) : \Sigma (f : S -> S.A -> \Prop) (isInj f) => (
  isElem-func __ __,
  isElem= __
)
  \where {
    --     \func set-singleton (s : S) : S.A -> \Prop => \lam a => S.isElem a s

    \func isElem-func (s : S) : S.A -> \Prop => S.isElem __ s

--     -- взаимно рекурсивные мб
--     -- равенство пропов очев
--     \func add-isElem= {s1 s2 : S} {a : S.A} (p : isElem-func s1 = isElem-func s2) : isElem-func (S.add a s1) = isElem-func (S.add a s2) =>
--       ext (\lam _ => <->_=.1 (one-side p __, one-side (inv p) __))
--       \where {
--         \func one-side {s3 s4 : S} {a' : S.A} (q : isElem-func s3 = isElem-func s4) (r : isElem-func (S.add a s3) a') : isElem-func (S.add a s4) a' =>
--           \case S.add-prop r \with {
--             | byLeft a=a' => transport (S.isElem __ (S.add a s4)) a=a' S.add-head
--             | byRight a_in_s3 => S.add-tail (transport id (unext q a') a_in_s3)
--           }
--       }
--
--     \func EqIsElem {S : SetSpec} (xs ys : S) : \Prop => \Pi (a : S.A) -> a S.`isElem` xs <-> a S.`isElem` ys
--
--     \func SetFactorized (S : SetSpec) : \Set => Quotient {S} EqIsElem
--
--     \func setFactorizedToSet {S : SetSpec} (xs : SetFactorized S) : S \elim xs
--       | in~ xs => xs
--       | ~-equiv xs ys r => {?}
--
--     \lemma in~-inj {S : SetSpec} : isInj (in~ {SetFactorized S})
--       => \lam {xs} {ys} p => \case \elim xs, \elim ys, \elim p \with {
--         | in~ xs, in~ ys, p => path $ ~-equiv xs ys \lam a =>
--             ( \lam q => isElem-In $ transport (a `isElem` __) p $ In-isElem q
--             , \lam q => isElem-In $ transportInv (a `isElem` __) p $ In-isElem q
--             )
--       }

    \func isElem= {s1 s2 : S} (p : isElem-func s1 = isElem-func s2) : s1 = s2 => S.set-ext {s1} {s2} (\lam a => <->_=.2 (unext p a))
  }


-- 4. Определите функцию isEmpty для ArraySet и для произвольного конечного множества

\func isEmptyArraySet {A : \Set} (xs : ArraySet A) : Bool \elim xs
  | in~ a => \case a \with {
    | nil => true
    | a1 :: l => false
  }-- EqArray in~ x in~ y
  | ~-equiv x y r => cases (x arg addPath, y arg addPath) \with {
    | nil, _, nil, q => idp
    | nil, p, :: a1 l : DArray (A : Fin (suc n) -> \Type), q => \have
      | in : In a1 (:: a1 l) => inP (0, idp)
      | eq : y = (:: a1 l) => q
      | in' : In a1 y => transport (In a1 __) (inv eq) in
      \in \case not-truncPEmpty $ TruncP.map ((r a1).2 in') (
        \lam i => \case transport id (pmap Fin (pmap (\lam arr => DArray.len {arr}) p)) i.1 \with {}
                                                            ) \with {}
    | a1 :: l, p, nil, q => \have -- copy-pasted
      | in : In a1 (:: a1 l) => inP (0, idp)
      | eq : x = (:: a1 l) => p
      | in' : In a1 x => transport (In a1 __) (inv eq) in
                            \in \case not-truncPEmpty $ TruncP.map ((r a1).1 in') (
        \lam i => \case transport id (pmap Fin (pmap (\lam arr => DArray.len {arr}) q)) i.1 \with {}
      ) \with {}
    | a1 :: l, _, a2 :: l1, _ => idp
  }

\func arraySetEquiv {S : FinSetSpec} : Equiv {ArraySet S.A} {S} => equality=>equivalence arraySet=Set

\func isEmptySet {S : FinSetSpec} (s : S) : Bool => isEmptyArraySet (Retraction.sec {arraySetEquiv} s)


-- 5. Определите функцию union {A : \Set} : S -> S -> S для ArraySet и для произвольного S (удовлетворяющего FinSetSpec)

-- \func arrayUnion {A : \Set} (a b : ArraySet A) : ArraySet A \elim a, b
--   | in~ a, in~ a1 => in~ $ a ++ a1
--   | in~ a, ~-equiv x y r => mcases
--   | ~-equiv x y r, in~ a => {?}

\func arrayUnion {A : \Set} (a b : ArraySet A) : ArraySet A \elim a
  | in~ a => \case b \with {
    | in~ b => in~ $ a ++ b
    -- (in~ $ a ++ x) = (in~ $ a ++ y)
    | ~-equiv x y r => Quotient.~-equiv {Array A} {EqArray} (a ++ x) (a ++ y) (\lam c =>
        \have
          | one-side {x' y' : Array A} (r' : EqArray x' y') : In c (a ++ x') -> In c (a ++ y') =>
            \case __ \with {
              | inP (x_index, p) => \case ++.split-index x_index \with {  -- lol ++_index-right signature is inconsistent with ++_index-left
                | inl (j, i=left_j) => inP (++.index-left j, ++.++_index-left j *> (inv $ ++.++_index-left j) *> pmap ((a ++ x') __) (inv i=left_j) *> p)
                | inr (j, i=right_j) => TruncP.map ((r' c).1 (inP (j, (inv $ ++.++_index-right {A} {a} {x'} {j}) *> pmap ((a ++ x') __) (inv i=right_j) *> p)))
                    (\lam (y_index, q) => (++.index-right {A} {a} {y'} y_index, ++.++_index-right {A} {a} {y'} {y_index} *> q))
              }
            }
        \in
          (
            one-side r,
            one-side (sym-EqArray r)
          ))
  }
  | ~-equiv x y r => cases b \with {
    | in~ a => Quotient.~-equiv {Array A} {EqArray} (x ++ a) (y ++ a) (\lam c =>  -- copy-paste
        \have
          | one-side {x' y' : Array A} (r' : EqArray x' y') : In c (x' ++ a) -> In c (y' ++ a) =>
            \case __ \with {
              | inP (x_index, p) => \case ++.split-index x_index \with {
                | inl (j, i=left_j) => TruncP.map ((r' c).1 (inP (j, (inv $ ++.++_index-left j) *> pmap ((x' ++ a) __) (inv i=left_j) *> p)))
                    (\lam (y_index, q) => (++.index-left {A} {y'} {a} y_index, ++.++_index-left y_index *> q))
                | inr (j, i=right_j) => inP (++.index-right j, ++.++_index-right {A} {y'} {a} {j} *> (inv $ ++.++_index-right {A} {x'} {a} {j}) *> pmap ((x' ++ a) __) (inv i=right_j) *> p)
              }
            }
        \in
          (
            one-side r,
            one-side (sym-EqArray r)
          ))
  }

\func union {S : FinSetSpec} (a b : S) : S => arraySetEquiv (arrayUnion (Retraction.sec {arraySetEquiv} a) (Retraction.sec {arraySetEquiv} b))

-- 6. Определите функцию intersection {A : DecSet} : S -> S -> S для ArraySet и для произвольного S (удовлетворяющего FinSetSpec)

\func index-dec' {A : DecSet} (l : Array A) (a : A) : Dec (In a l) =>
  \case index-dec l a \with {
  | inl index : Index a a' => yes $ inP index
  | inr notIndex => no (\lam i => not-truncPEmpty $ TruncP.map i (\lam _x => notIndex _x))
}

\func arrayIntersection {A : DecSet} (a b : ArraySet A) : ArraySet A \elim a
  | in~ a => \case b \with {
    | in~ b => in~ $ keep (index-dec' b __) a
    | ~-equiv x y r => Quotient.~-equiv {Array A} {EqArray} (keep (index-dec' x) a) (keep (index-dec' y) a) (\lam c =>
        \have
          | one-side {x' y' : Array A} (r' : EqArray x' y') : In c (keep (index-dec' x') a) -> In c (keep (index-dec' y') a) =>
            \case __ \with {
              | inP (x_index, p) => TruncP.map ((r' c).1 (
                \have index => keep.satisfies (index-dec' x' __) {a} {x_index}
                \in TruncP.map index (\lam (ind, q) => (ind, q *> p))
                                                         )) (\lam (y_index, q) => \have
                | (j, preim-q) => keep.preimage x_index
                | ajc : c = a j => inv p *> preim-q
                | pp : In (a j) y' => inP (y_index, q *> ajc)
                | in : Index (a j) (keep (index-dec' y') a) => keep.element pp
                                                                                  \in (in.1, in.2 *> inv ajc))
            }
        \in
          (
            one-side r,
            one-side (sym-EqArray r)
          ))
  }
  | ~-equiv x y r => cases b \with {
    | in~ b => Quotient.~-equiv {Array A} {EqArray} (keep (index-dec' b) x) (keep (index-dec' b) y) (\lam c =>
        \have
          | one-side {x' y' : Array A} (r' : EqArray x' y') : In c (keep (index-dec' b) x') -> In c (keep (index-dec' b) y') =>
            \case __ \with {
              | inP (x_index, p) => \have
                | satis : In (keep (index-dec' b) x' x_index) b => keep.satisfies (index-dec' b __) {x'} {x_index}
                | c_in_b : In c b => transport (In __ b) p satis
                | (j, q-preim) => keep.preimage x_index
                                    \in TruncP.map ((r' c).1 (inP (j, inv q-preim *> p))) (\lam (y_index, q) =>
                \have
                  | pp : In (y' y_index) b => transport (In __ b) (inv q) c_in_b
                  | (elem, q-elem) => keep.element {A} {In __ b} {index-dec' b __} {y'} {y_index} pp
                \in (elem, q-elem *> q)
                                                                                          )
            }
        \in
          (
            one-side r,
            one-side (sym-EqArray r)
          ))
  }

\func intersection {A : DecSet}  {S : FinSetSpec {A}} (a b : S) : S => arraySetEquiv (arrayIntersection (Retraction.sec {arraySetEquiv} a) (Retraction.sec {arraySetEquiv} b))

-- 7. Мы не можем определить функцию size в общем случае, но мы можем определить предикат S -> Nat -> \Prop,
--    соответствующий \lam xs n => size xs <= n
--    a) Определите описанный предикат
--    b) Определите функцию size из лекции
--    c) Докажите, что size-le эквивалентно определению через size, если A -- разрешимо и S -- конечно

\func size-le {S : SetSpec} (s : S) (n : Nat) : \Prop => ∃ (f : Fin n -> \Sigma (a : S.A) (a S.`isElem` s)) (isSurj f)

-- \func count {A : DecSet} (l : Array A) : Nat => DArray.len {nub l}

\func sym-EqArray {A : \Set} {xs ys : Array A} (p : EqArray xs ys) : EqArray ys xs => \lam a => <->sym (p a)

\func nub-EqArray {A : DecSet} {xs ys : Array A} (p : EqArray xs ys) : EqArray (nub xs) ys => \lam a => (
  \lam i => TruncP-flatMap i (\lam (j, q) => \have (c, d) => nub-preimage j \in (p a).1 (inP (c, inv d *> q))),
  \lam i => TruncP-flatMap i (\lam (j, q) => TruncP.map ((p a).2 (inP (j, q))) (\lam (c, d) => \have e => nub-isSurj xs c \in (e.1, e.2 *> d)))
)

\lemma nub-len<= {A : DecSet} {xs ys : Array A} (p : EqArray (nub xs) ys) : DArray.len {nub xs} NatSemiring.<= DArray.len {ys} =>
  FinSet.FinCardInj f' f-inj
  \where {
    \func f (ind : Fin (DArray.len {nub xs})) : Index ((nub xs) ind) ys =>
--       (p ((nub xs) ind)).1 (\have preimage => nub-preimage ind \in inP ({?} preimage.1, inv preimage.2))
        \case find (dec_decide $ DecSet.decideEq ((nub xs) ind) __) ys \with {
          | inl (j, pj, _) => (j, inv pj)
          | inr c => absurd (emp ind c)
        }

    \func emp (ind : Fin (DArray.len {nub xs})) (c : \Pi {j : Fin ys.len} -> dec_decide (A.decideEq (nub xs ind) (ys j)) -> Empty): Empty =>
      not-truncPEmpty (TruncP.map ((p ((nub xs) ind)).1 (inP (ind, idp))) (\lam (i, r) => c {i} (inv r)))

    \func f' (ind : Fin (DArray.len {nub xs})) : Fin (DArray.len {ys}) => (f ind).1

    \func f-inj : isInj f' => \lam {a} {a'} (p1 : (f a).1 = (f a').1) =>
        \have
--           | q : (f a) = transport (ys __ = (nub xs) a') p1 (f a') => ext p1 p
            | q : ys (f a).1 = ys (f a').1 => pmap ys p1
            | q' : (nub xs) a = (nub xs) a' => \have name : ys (f a).1 = (nub xs) a => (f a).2 \in (inv (f a).2) *> q *> ((f a').2)
--           | q : (nub xs) a = (f a).1 => idp
--           | q : (nub xs) a = (nub xs) a' => p1
        \in nub-isInj q'

--         cases (find (dec_decide $ DecSet.decideEq ((nub xs) a) __) ys arg addPath, find (dec_decide $ DecSet.decideEq ((nub xs) a') __) ys arg addPath) \with {
--           | inl (j, pj, _x), p, inl (j', pj', _), p' => cases ((j, inv pj) arg addPath, (j', inv pj') arg addPath) \with {
--             | (j2,pj2), p2, (j3,pj3), p3 => \have
--               | r : j = (j2, pj2).1 => pmap __.1 p2
--               | r1 : j = (j, inv pj).1 => r *> pmap __.1 (inv p2)
--               | r2 : find (dec_decide $ DecSet.decideEq ((nub xs) a) __) ys = (inl ((j, inv pj).1, pj, _x)) => {?} -- transport (\lam j'' => find (dec_decide $ DecSet.decideEq ((nub xs) a) __) ys = (inl ((j'', inv pj).1, pj, _x))) r1 p
--               | r3 : (f a).1 = j => r2
--                                             \in {?}
--           }
--           | _, _, inr c, _ => absurd (emp a' c)
--           | inr c, _, _, _ => absurd (emp a c)
--         }
  }

\func size {A : DecSet} {S : FinSetSpec {A}} (s : S) : Nat => \case Retraction.sec {arraySetEquiv} s \with {
  | in~ a => DArray.len {nub a}
  | ~-equiv x y r => \have
    | nub-eq : EqArray (nub y) x => nub-EqArray (sym-EqArray r)
    | nub-eq' : EqArray (nub x) (nub y) => nub-EqArray (sym-EqArray nub-eq)
                     \in <=-antisymmetric (nub-len<= nub-eq') (nub-len<= (sym-EqArray nub-eq'))
}

\func size=>size-le {A : DecSet} {S : FinSetSpec {A}} {n : Nat} (s : S) : size s NatSemiring.<= n = size-le s n =>
  <->_=.1 (
    \lam size<=n => \case Retraction.sec {arraySetEquiv} s \with {
      | in~ a => \have
      p : size s = DArray.len {nub a} => idp
  \in {?}
    },
    {?}
          )


-- Optional
-- 8. Определите предикат isFin : \Type -> \Prop так,
--    чтобы множество \Sigma (P : A -> \Prop) (isFin (\Sigma (a : A) (P a))) удовлетворяло FinSetSpec
--    Определите этот инстанс

\func isFin (A : \Type) : \Prop => ∃ (n : Nat) (f : Fin n -> A) (isSurj f)  -- could use Array

\func Evidence {A : \Type} (P : A -> \Prop) => \Sigma (a : A) (P a)

\func ProofIsFin {A : \Type} (P : A -> \Prop) : \Prop => isFin (Evidence P)

\func LimitedSet (A : \Type) : \Set => Quotient {\Sigma (P : A -> \Prop) (ProofIsFin P)} (\lam _x _x1 => _x.1 = _x1.1) -- (isFin (\Sigma (a : A) (P a)))

-- \func LimitedSet' (A : \Type) (P : A -> \Prop) : \Prop => LimitedSet A P

\func ExtendedDomain {A : \Set} (P : A -> \Prop) (new-a : A) : A -> \Prop => \lam a => (new-a = a) || P a

\func extend-func {A : \Set} {n : Nat} {P : A -> \Prop} (f : Fin n -> Evidence P) (a : A) : Fin (suc n) -> Evidence (ExtendedDomain P a) =>
  \case __ \with {
    | 0 => (a, byLeft idp)
    | suc f1 => ((f f1).1, byRight (f f1).2)
  }

\func extend-func-surj {A : \Set} {n : Nat} {P : A -> \Prop} {f : Fin n -> Evidence P} (a : A) (p : isSurj f) : isSurj (extend-func f a) =>
  \lam (a, extP) => \case extP \with {
    | byLeft a1 => inP (0, cases (extend-func f a 0) \with {

    })
    | byRight b => TruncP.map (p (a, b)) (\lam (x, q) => (suc x, {?}))
  }

\instance LimitedSetSet {A : \Set} : FinSetSpec {A} (LimitedSet A)
  | isElem (a : A) (s : LimitedSet A) : \Prop \elim s {
    | in~ s => s.1 a
    | ~-equiv x y r => unext r a
  }
  | set-ext {xs ys : LimitedSet A} (p : \Pi (a : A) -> a `isElem` xs <-> a `isElem` ys) : xs = ys \elim xs, ys {
    | in~ xs, in~ ys =>
      \have
        | q (a : A) : xs.1 a = ys.1 a => <->_=.1 (p a)
      \in ~-pequiv (ext q)
  }
  | empty : LimitedSet A => in~ (\lam a => Empty, inP (0, \case __ \with {}, \lam (a, e) => absurd e))
  | empty-prop {a : A} : Not (a `isElem` empty) => \lam e => e
  | add (a : A) (s : LimitedSet A) : LimitedSet A \elim s {
    | in~ s =>
      in~ (\lam a1 => (a = a1) || s.1 a1, TruncP.map s.2 (\lam (n, f, p) => (suc n, extend-func f a, extend-func-surj a p)))
    | ~-equiv x y r => ~-pequiv (ext (\lam a1 => pmap {\Prop} {\Type} ((a = a1) || __) (unext r a1)))
  }
  | add-head {x : A} {xs : LimitedSet A} : x `isElem` add x xs \elim xs {
    | in~ xs => \have q : x `isElem` add x (in~ xs) => byLeft idp \in q
  }
  | add-tail {x y : A} {xs : LimitedSet A} (p : x `isElem` xs) : x `isElem` add y xs \elim xs {
    | in~ xs => \have q : x `isElem` add y (in~ xs) => byRight p \in q
  }
  | add-prop {x y : A} {xs : LimitedSet A} (p : y `isElem` add x xs) : (x = y) || y `isElem` xs \elim xs {
    | in~ xs => \have q : (x = y) || y `isElem` in~ xs => p \in q
  }
  | set-fin (s : LimitedSet A) : ∃ (xs : Array A) (\Pi (a : A) -> In a xs <-> a `isElem` s) \elim s {
    | in~ s =>
      TruncP.map s.2 (\lam (n, f, q) => (\lam j => (f j).1, \lam c => (
        \lam i => \case TruncP.map i (\lam in => transport s.1 in.2 (f in.1).2) \with {
          | inP a => a
        },
        \lam _x => TruncP.map (q (c, _x)) (\lam _x1 => (_x1.1, pmap __.1 _x1.2)))))
  }

-- Optional
-- 9. Определите NubArraySet (ArraySet без повторений) и инстанс FinSetSpec для него

\func NubArray (A : DecSet) : \Set => \Sigma (l : Array A) (nub l = l)

\func nubArray {A : DecSet} (l : Array A) : NubArray A => (nub l, nub_id nub-isInj)

\func NubArraySet (A : DecSet) : \Set => Quotient {NubArray A} (\lam n n1 => EqArray n.1 n1.1)

\func nubArraySetToSet {A : DecSet} {S : SetSpec {A}} (xs : NubArraySet A) : S \elim xs
  | in~ (xs, _) => arrayToSet xs
  | ~-equiv xs ys r => set-ext \lam a =>
      ( \lam p => In-isElem $ (r a).1 $ isElem-In p
      , \lam p => In-isElem $ (r a).2 $ isElem-In p
      )

\lemma nubArraySetToSet-inj {A : DecSet} {S : SetSpec {A}} : isInj (nubArraySetToSet {A} {S})
  => \lam {xs} {ys} p => \case \elim xs, \elim ys, \elim p \with {
    | in~ xs, in~ ys, p => path $ ~-equiv xs ys \lam a =>
        ( \lam q => isElem-In $ transport (a `isElem` __) p $ In-isElem q
        , \lam q => isElem-In $ transportInv (a `isElem` __) p $ In-isElem q
        )
  }

\lemma In-nub-isElem {A : DecSet} {S : SetSpec {A}} {xs : Array A} {a : A} (p : In a xs) : S.isElem a (arrayToSet (nub xs)) =>
  In-isElem (TruncP.map p (\lam (i, q) => \have
    | (j, r) => nub-isSurj xs i
                                          \in (j, r *> q)))

\lemma isElem-nub-In {A : DecSet} {S : SetSpec {A}} {xs : Array A} {a : A} (p : S.isElem a (arrayToSet (nub xs))) : In a xs =>
  TruncP.map (isElem-In p) (\lam (i, q) => \have
    | (j, r) => nub-preimage i
                                           \in (j, inv r *> q))

\lemma nubArraySetToSet-surj {A : DecSet} {S : FinSetSpec {A}} : isSurj (nubArraySetToSet {A} {S})
  => \lam s => \case set-fin s \with {
    | inP (xs, p) => inP (in~ (nubArray xs), set-ext \lam x =>
        ( \lam q => (p x).1 $ isElem-nub-In q
        , \lam q => In-nub-isElem $ (p x).2 q
        ))
  }

\func nubArraySetToSet=Set {A : DecSet} {S : FinSetSpec {A}} : NubArraySet A = S
  => QEquiv-to-= $ Equiv.fromInjSurj nubArraySetToSet nubArraySetToSet-inj nubArraySetToSet-surj

\func inst {A : DecSet} : FinSetSpec {A} (NubArraySet A) => transport (FinSetSpec {A} __) (inv (nubArraySetToSet=Set {A} {ArraySetSet {A}})) (ArraySetSet {A})
